baseURL = 'https://blog.vikin007.xyz'
languageCode = 'en-us'
title = "Yumeki's Hugo"
theme = 'ananke'
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # 允许原始 HTML

[menu]
  [[menu.main]]
    name = "About"
    url = "/DIR01/"
    weight = 1
  [[menu.main]]
    name = "Articles"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Contact"
    url = "/DIR02/"
    weight = 3
	




[params]
  featured_image = "https://blog.vikin007.xyz/images/screenshot.png"
  description = "Write something, for yourself, for everyone."