baseURL = 'https://shanmengqi2.github.io/hugo_quickstart/'
languageCode = 'en-us'
title = "Yumeki's Hugo"
theme = 'ananke'

[params]
  images = ["default.jpg"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # 允许原始 HTML

